version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travelingweb
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
  
  php_backend:
    build: ./backend
    container_name: php_backend
    depends_on:
      - mysql_db
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html 

  react_frontend:
    build: ./frontend/frontend
    container_name: react_frontend
    depends_on:
      - php_backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/frontend:/app        
      - /app/node_modules                

volumes:
  db_data:
